language: rust
dist: xenial
sudo: false

os:
- linux
- osx

rust:
  - 1.51.0

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty
    packages:
      - g++
      - llvm-dev
      - libclang-dev
      - clang

cache: cargo

install:
  - rustup component add rustfmt
  - rustfmt -V

script:
  - cargo fmt --all -- --check
  - cargo test --manifest-path=librocksdb-sys/Cargo.toml
  - cargo test
