language: rust
dist: bionic

os:
- linux
- osx

rust:
  - 1.51.0

install:
  - rustup component add rustfmt
  - rustfmt -V
  - rustup component add clippy
  - cargo clippy --version

script:
  - cargo fmt --all -- --check
  - make clippy
  - cargo test --manifest-path=librocksdb-sys/Cargo.toml
  - cargo test -- --skip test_iterator_outlive_db
